# Generated by Django 5.1.2 on 2024-10-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_profile_image_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Femail', 'Femail'), ('Custom', 'Custom')], default='Mail', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Other', 'Other')], default='Muslim', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default=1, upload_to='authentication/images/'),
            preserve_default=False,
        ),
    ]
