# Generated by Django 5.1.2 on 2024-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0003_publictransport_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransport',
            name='schedules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
