# Generated by Django 5.1.2 on 2024-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0005_publictransport_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransport',
            name='bus_img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
