# Generated by Django 5.1.2 on 2024-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
