# Generated by Django 5.1.2 on 2024-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0004_remove_trafficupdate_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficupdate',
            name='status',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Moderate Traffic', 'Moderate Traffic'), ('Heavy Traffic', 'Heavy Traffic')], max_length=50),
        ),
    ]
